"""add_submission_unique_constraint

Revision ID: 4aea84fbd758
Revises: 8e3d23ce67c9
Create Date: 2026-09-07 16:14:51.113949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4aea84fbd758'
down_revision: Union[str, None] = '8e3d23ce67c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_submission_student_assignment_task', 'submissions', ['student_id', 'test_assignment_id', 'task_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_submission_student_assignment_task', 'submissions', type_='unique')
    # ### end Alembic commands ###
