"""add submission_student_id

Revision ID: d1a584e38889
Revises: e61f9b21146e
Create Date: 2026-08-29 20:25:38.328854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1a584e38889'
down_revision: Union[str, None] = 'e61f9b21146e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('student_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_submissions_student_id_users'), 'submissions', 'users', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_submissions_student_id_users'), 'submissions', type_='foreignkey')
    op.drop_column('submissions', 'student_id')
    # ### end Alembic commands ###
