"""refactoring

Revision ID: e61f9b21146e
Revises: 6f8cdd1376dc
Create Date: 2026-08-29 20:01:00.302447

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e61f9b21146e'
down_revision: Union[str, None] = '6f8cdd1376dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('test_assignment_id', sa.Integer(), nullable=False))
    op.create_foreign_key(op.f('fk_submissions_test_assignment_id_test_assignments'), 'submissions', 'test_assignments', ['test_assignment_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_submissions_test_assignment_id_test_assignments'), 'submissions', type_='foreignkey')
    op.drop_column('submissions', 'test_assignment_id')
    # ### end Alembic commands ###
