"""add role to user table

Revision ID: a35b1ae80a1a
Revises: 9ed7bfe74e0e
Create Date: 2026-08-25 18:06:52.516938

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a35b1ae80a1a"
down_revision: Union[str, None] = "9ed7bfe74e0e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "role",
            sa.Enum("STUDENT", "TEACHER", "ADMIN", name="user_role_enum"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "role")
    # ### end Alembic commands ###
