"""delete user_id from submission

Revision ID: 8e3d23ce67c9
Revises: d1a584e38889
Create Date: 2026-08-30 15:13:38.900324

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e3d23ce67c9'
down_revision: Union[str, None] = 'd1a584e38889'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_submissions_user_id_users', 'submissions', type_='foreignkey')
    op.drop_column('submissions', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_submissions_user_id_users', 'submissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
