"""add assignment students

Revision ID: 2ee893b10b66
Revises: 4aea84fbd758
Create Date: 2026-09-08 10:29:27.640766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ee893b10b66'
down_revision: Union[str, None] = '4aea84fbd758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    assignment_status_enum = postgresql.ENUM(
        "assigned",
        "in_progress",
        "completed",
        "overdue",
        name="assignment_status",
        create_type=False,
    )

    op.create_table(
        "assignment_students",
        sa.Column("assignment_id", sa.Integer(), nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),

        sa.Column(
            "status",
            assignment_status_enum,
            nullable=False,
        ),

        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column(
            "completed_at",
            sa.DateTime(timezone=True),
            nullable=True,
        ),
        sa.Column("id", sa.Integer(), nullable=False),

        sa.ForeignKeyConstraint(
            ["assignment_id"],
            ["test_assignments.id"],
            name=op.f(
                "fk_assignment_students_assignment_id_test_assignments"
            ),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["users.id"],
            name=op.f(
                "fk_assignment_students_student_id_users"
            ),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint(
            "id",
            name=op.f("pk_assignment_students"),
        ),
        sa.UniqueConstraint(
            "assignment_id",
            "student_id",
            name="uq_assignment_student",
        ),
    )
    
def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assignment_students')
    # ### end Alembic commands ###
