"""new tables

Revision ID: 6f8cdd1376dc
Revises: a35b1ae80a1a
Create Date: 2026-08-28 19:10:36.246796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6f8cdd1376dc'
down_revision: Union[str, None] = 'a35b1ae80a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects')),
    sa.UniqueConstraint('name', name=op.f('uq_subjects_name'))
    )
    op.create_index(op.f('ix_subjects_slug'), 'subjects', ['slug'], unique=True)
    op.create_table('groups',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_groups_teacher_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_groups'))
    )
    op.create_table('tests',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name=op.f('fk_tests_created_by_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tests'))
    )
    op.create_table('topics',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_topics_subject_id_subjects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_topics')),
    sa.UniqueConstraint('subject_id', 'name', name='uq_topic_subject_name')
    )
    op.create_table('enrollments',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_enrollments_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_enrollments_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_enrollments')),
    sa.UniqueConstraint('student_id', 'group_id', name='uq_enrollment_student_group')
    )
    op.create_table('test_assignments',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('assigned', 'in_progress', 'completed', 'overdue', name='assignment_status'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.CheckConstraint('(student_id IS NOT NULL) != (group_id IS NOT NULL)', name=op.f('ck_test_assignments_ck_test_assignment_target_xor')),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['users.id'], name=op.f('fk_test_assignments_assigned_by_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_test_assignments_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_test_assignments_student_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('fk_test_assignments_test_id_tests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_assignments'))
    )
    op.create_table('test_tasks',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], name=op.f('fk_test_tasks_task_id_tasks'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('fk_test_tasks_test_id_tests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_test_tasks')),
    sa.UniqueConstraint('test_id', 'task_id', name='uq_test_task')
    )
    op.create_table('ai_analyses',
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('feedback', sa.Text(), nullable=False),
    sa.Column('weak_topics', sa.JSON(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name=op.f('fk_ai_analyses_submission_id_submissions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analyses')),
    sa.UniqueConstraint('submission_id', name=op.f('uq_ai_analyses_submission_id'))
    )
    op.drop_table('ai_analysiss')
    op.add_column('tasks', sa.Column('topic_id', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('body', sa.Text(), nullable=False))

    # --- явное создание enum-типов перед их использованием в add_column ---
    task_type_enum = sa.Enum('single_choice', 'multiple_choice', 'open_answer', name='task_type')
    task_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('tasks', sa.Column('task_type', task_type_enum, nullable=False))

    task_difficulty_enum = sa.Enum('easy', 'medium', 'hard', name='task_difficulty')
    task_difficulty_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('tasks', sa.Column('difficulty', task_difficulty_enum, nullable=False))
    # --- конец блока с enum ---

    op.add_column('tasks', sa.Column('correct_answer', sa.Text(), nullable=False))
    op.alter_column('tasks', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'title',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_index('ix_tasks_topic', table_name='tasks')
    op.drop_constraint('fk_tasks_created_by_id_users', 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tasks_created_by_id_users'), 'tasks', 'users', ['created_by_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('fk_tasks_topic_id_topics'), 'tasks', 'topics', ['topic_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('tasks', 'description')
    op.drop_column('tasks', 'topic')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('topic', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('tasks', sa.Column('description', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_tasks_topic_id_topics'), 'tasks', type_='foreignkey')
    op.drop_constraint(op.f('fk_tasks_created_by_id_users'), 'tasks', type_='foreignkey')
    op.create_foreign_key('fk_tasks_created_by_id_users', 'tasks', 'users', ['created_by_id'], ['id'], ondelete='CASCADE')
    op.create_index('ix_tasks_topic', 'tasks', ['topic'], unique=False)
    op.alter_column('tasks', 'title',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.alter_column('tasks', 'created_by_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tasks', 'correct_answer')
    op.drop_column('tasks', 'difficulty')
    op.drop_column('tasks', 'task_type')
    op.drop_column('tasks', 'body')
    op.drop_column('tasks', 'topic_id')

    # --- удаление enum-типов при откате ---
    sa.Enum(name='task_difficulty').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='task_type').drop(op.get_bind(), checkfirst=True)
    # --- конец блока с enum ---

    op.create_table('ai_analysiss',
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('feedback', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('weak_topics', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('submission_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], name='fk_ai_analysiss_submission_id_submissions', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_ai_analysiss'),
    sa.UniqueConstraint('submission_id', name='uq_ai_analysiss_submission_id')
    )
    op.drop_table('ai_analyses')
    op.drop_table('test_tasks')
    op.drop_table('test_assignments')
    op.drop_table('enrollments')
    op.drop_table('topics')
    op.drop_table('tests')
    op.drop_table('groups')
    op.drop_index(op.f('ix_subjects_slug'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###